plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.wearbridge'
version = '0.1.0'

android {
  namespace "expo.modules.wearbridge"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
}

dependencies {
  // 폰↔워치 통신 (Data Layer / Message API)
  implementation 'com.google.android.gms:play-services-wearable:18.2.0'
}
